 	public class NameAge {
      public static void main(String[] args) {
           Scanner scanner = new Scanner(System.in);
           System.out.print("Enter Name: ");
           String name = scanner.nextLine();
           System.out.print("Enter Age: ");
           int age = scanner.nextInt();
           System.out.println("Name: "+ name + " age: " + age);
           scnner.close();
     }
 }